## Disclaimer

> General Terms and Conditions

This website is hosted by the OECD Directorate for Science, Technology
and Industry. It is responsible for the content of this site. The
information published on this website have not been reviewed by the
Organisation and do not necessarily represent the official views of
the Organisation or of the governments of its member countries.

By making use of this website, you are explicitly declaring that you
agree to the following general terms and conditions:

> Intellectual Property Rights

The information content of this site can be freely used as such for
non-commercial purposes, on condition that OECD is identified as the
original author. No rights may be derived from the content of these
information, however. For uses other than that stated above, please
contact
[stan.contact@oecd.org](mailto:stan.contact@oecd.org?subject=STI/EAS%20Indicators)

> Limitation of Liability

The directorate aims to achieve current and reliable indicators on
this website. Despite the large degree of attention we put into the
data compilation on this site, we cannot guarantee that the
information is always correct or complete. If the information provided
contains inaccuracies, the directorate will make every effort to
rectify this as quickly as possible.

The directorate cannot be held liable, however, for direct
or indirect loss occurring as a result of the information on
this site. Please notify the directorate of any inaccuracies
or incomplete information:
[stan.contact@oecd.org](mailto:stan.contact@oecd.org?subject=STI/EAS%20Indicators)

The content of this site can be amended, changed or supplemented at
any time without notification or announcement. The directorate does
not provide any guarantee of the proper operation of the website and
cannot be held liable in any way for any poor operation or temporary
nonavailability of the website, or for any form of loss, direct or
indirect, which may ensue from access to or use of the website,
including all losses, work interruptions, damage to programs or other
data on the computer system, to equipment, software or other property
of the user.

> Maps and Territories

This website and any map included herein are without prejudice to the
status of or sovereignty over any territory, to the delimitation of
international frontiers and boundaries and to the name of any
territory, city or area.

> Information on the data for Israel appearing in OECD documents and publications

The statistical data for Israel are supplied by and under the
responsibility of the relevant Israeli authorities. The use of such
data by the OECD is without prejudice to the status of the Golan
Heights, East Jerusalem and Israeli settlements in the West Bank under
the terms of international law.

